"""empty message

Revision ID: 5122f25a65ed
Revises: f408ba3c2c60
Create Date: 2024-05-09 21:48:07.826744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5122f25a65ed'
down_revision = 'f408ba3c2c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_key', sa.String(length=50), nullable=False))
        batch_op.drop_column('answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('answer_key')

    # ### end Alembic commands ###
