"""empty message

Revision ID: d6b1258419e5
Revises: 73c4502d60f5
Create Date: 2024-05-08 13:55:43.554169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b1258419e5'
down_revision = '73c4502d60f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('total_items',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.alter_column('total_items',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
