"""empty message

Revision ID: f408ba3c2c60
Revises: d6b1258419e5
Create Date: 2024-05-09 21:46:14.073030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f408ba3c2c60'
down_revision = 'd6b1258419e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('option1', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('option2', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('option3', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('option4', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('option4')
        batch_op.drop_column('option3')
        batch_op.drop_column('option2')
        batch_op.drop_column('option1')

    # ### end Alembic commands ###
